<?php if ($block->isStockStatusLabelEnabled()) : ?>

    <?php /* @noEscape */ echo $block->getStyle(); ?>
    <label id="stock_status_label"></label>

    <script type="text/x-magento-init">
    {
        "#stock_status_label": {
            "Lucasart_StockStatusLabel/js/stock-status-label": {
                "productOptions": <?php /* @noEscape */ echo $block->getProductOptions() ?>,
                "productData": <?php /* @noEscape */ echo $block->getProductData() ?>,
                "labels": <?php /* @noEscape */ echo $block->getLabelTexts() ?>
            }
        }
    }
    </script>

<?php endif; ?>
