<?php if ( $block->isStockStatusLabelEnabled() ) { ?>

    <?php echo $block->getStyle(); ?>
    <label id="stock_status_label"></label>

    <script type="text/x-magento-init">
    {
        "*": {
            "LucasArt_StockStatusLabel/js/stock-status-label": {
                "swatchOptions": <?php echo $block->getSwatchOptions() ?>,
                "productData": <?php echo $block->getProductData() ?>,
                "labels": <?php echo $block->getLabelTexts() ?>
            }
        }
    }
    </script>

<?php } ?>
